MyWiki/MyWiki/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('wiki.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyWiki/wiki/urls.py
from django.urls import path, include, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static
# URL configuratrion for the sites pages.
# This has been done dynamically instead of use of absolute url
app_name = 'wiki'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'), # Navigation for the index page.
    path('errors/407', views.test_407_error , name='test_407_error'), # Used to ensure the 407 warning doesnt appear in the log.
    path('errors/500', views.test_500_error , name='test_500_error'), # Used to ensure the 407 error appears in the log.
    path('errors/404', views.test_404_error , name='test_404_error'), # Used to ensure the 404 warning appears in the log.
    path('download/upload/<str:path>/', views.download, name='download'),
    path('upload/', views.upload_file, name='upload_page' ), # Navigation for the file upload page.
    path('accounts/signup', views.signup_page , name='signup_page'), # Navigation for the user signup page.
    path('<str:pk>/edit/save', views.save_page , name='save_page'), # calls the save page function in views.
    path('<str:pk>/edit/delete/confirm', views.delete_confirm , name='delete_confirm'), # calls the delete page function in views.
    path('<str:pk>/edit/delete', views.delete_page , name='delete_page'), # Navigation for the confirmation page.
    path('<str:pk>/edit', views.edit_page , name='edit_page'), # Navigation for the page modification.
    path('<str:pk>/', views.View_Page, name='detail'), # Navigation for each page view created.
]
# URL configuratrion for the sites accounts login sections.
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

MyWiki/wiki/models.py
from django.db import models
from django.urls import reverse
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class Page(models.Model):
    title = models.CharField(max_length=64, primary_key=True) # Defines the pages title and applies parameters to limit word count and to make it the primary field of the database.
    content = models.TextField() # Adds a text field for the pages content. No extra parameters are needed for this at this time.
    counter = models.IntegerField(default=1) # defines the word counter using interger values which is default to 1. This will be saved to the database and will record a pages visits.

    
    def __str__(self):
        return self.title # returns the title.

    def get_absolute_url(self):
        return reverse('wiki:detail', args=[self.title]) # Proviedes the detail view with the args 'title'

# User form for members to signup.
class SignUpForm(UserCreationForm):

    # Adds a character field to the form with a label, max length, help text and a placeholder.
    username = forms.CharField(label='Username', max_length=30, required=True, help_text='Please choose a username.', widget=forms.TextInput(attrs={'placeholder': 'Username'})) 
    first_name = forms.CharField(label='Forename', max_length=30, required=False, help_text='Optional.') # Adds a character field to the form with a label, max length and some help text.
    last_name =  forms.CharField(label='Surname', max_length=30, required=False, help_text='Optional.' )# Adds a character field to the form with a label, max length and some help text.
    email =      forms.EmailField(label='Email', max_length=254, required=True, help_text='Required. Inform a valid email address.') # Adds a character field to the form with a label, max length and some help text.
    password1 =  forms.CharField(label='Password', max_length=30, required=True, help_text='Required.') # Adds a character field to the form with a label, max length and some help text.
    password2 =  forms.CharField(label='Confirm Password', max_length=30, required=True, help_text='Required.') # Adds a character field to the form with a label, max length and some help text.

    class Meta:
        model = User # Defines a model 'User'
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2', ]

class UserFileUpload(models.Model):
    upload = models.FileField(upload_to='upload/') # Defines a file field for use on the forms.py and the file upload page.

    def __str__(self):
        return self.upload.name # returns the upload name

MyWiki/wiki/forms.py
from django.forms import ModelForm
from .models import UserFileUpload
from django import forms

# A form used to setup the file upload system.
class UploadFileForm(ModelForm):
    class Meta:
        model = UserFileUpload # creates the model UserFileUpload
        fields = ['upload'] # Defines the field 'upload'
        widgets = { # Styles the form to give it a more appearling design. Extended on the template.
            "upload": forms.ClearableFileInput(
                attrs={
                    'size':'30',
                    'style':'position:relative; z-index: 100; padding-top:10px; padding-bottom:10px; padding-left:17%; padding-right:17%; line-height: 0px;',
                }),
        } 

MyWiki/wiki/views.py
import os
from django.conf import settings
from django.views import generic
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.http import HttpResponse, Http404
from django.db.models import F

from .forms import UploadFileForm
from .models import Page, SignUpForm, UserFileUpload

# Sets the view for the index page.
class IndexView(generic.ListView):
    template_name = 'wiki/index.html'
    context_object_name = 'pages'

    def get_queryset(self):
        return Page.objects.filter()

# Previous method of viewing pages now updated in View_Page
#class DetailView(generic.DetailView):
#    model = Page
#    template_name = 'wiki/detail.html'

#    def get_queryset(self):
#        return Page.objects.filter()

def View_Page(request, pk):
    try:
        page = Page.objects.get(pk=pk) # Gets the pages primary key - title
        page.counter = F('counter') + 1 # adds 1 to the pages counter
        page.save(update_fields=['counter']) # saves this value to the database
        page.refresh_from_db() # Refreshes the value from the database
        return render(request, 'wiki/detail.html', {'page': page}) # Renders the desired page.

    except Page.DoesNotExist:
        return render(request, 'wiki/create_page.html', {'page_name': pk}) # Navigate to page creation if it doesnt exist.

@login_required
def edit_page(request, pk):
    try:
        page = Page.objects.get(pk=pk) # Gets the pages title
        content = page.content # Gets the pages content
    except Page.DoesNotExist: # if the page doesn't exist default the content to an empty string
        content = ""

    return render(request, 'wiki/edit_page.html', # Render the edit page
    {
        'page_name': pk,
        'content': content
    })

@login_required
def save_page(request, pk):
    content = request.POST['content']
    try:
        page = Page.objects.get(pk=pk) # Gets the pages title
        page.content = content # Gets the pages content
    except Page.DoesNotExist:  # if the page doesn't exist create it.
        page = Page(title=pk, content=content)
    if 'Save' in request.POST: # if gets post `Save` then save the pages content and update the database
        page.save()
    return redirect(page) # redirect to the page

@login_required
def delete_page(request, pk):
    try:
        Page.objects.get(pk=pk) # Gets the pages title
        return render(request, "wiki/delete_page.html", # renders the page deletion confirmation page
        {
            'page_name': pk
        })
    except Page.DoesNotExist: # if the page doesnt exist return to the index page
        return redirect('wiki:index')

@login_required
def delete_confirm(request, pk):
    page = Page.objects.get(pk=pk)  # Gets the pages title
    if 'Delete' in request.POST:
        page.delete() # if gets post `delete` then delete the page and remove it from the database
    return redirect('wiki:index') # redirect the user to the index page.

def signup_page(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST) # gets the Signupform from models.py
        if form.is_valid(): # checks if the form is valid
            form.save() # save it to the database
            username = form.cleaned_data.get('username') # use the signup credentials
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user) #s signin to the newly created page
            return redirect('wiki:index') #render the index page as is_authenicated
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})

# adds the ability to upload files to the page
@login_required
def upload_file(request):
    context = {}
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid(): # checks if the form is valid before saving it
            form.save() # save the form
    else:
        form = UploadFileForm()
    context['form'] = form
    context['files'] = UserFileUpload.objects.all().order_by('upload') # display the files on the page ordered by upload order
    return render(request, 'wiki/upload.html', context) # renderes the upload page with the uploaded files


def download(request, path):
    file_path = os.path.join(settings.MEDIA_ROOT + '/upload', path)
    if os.path.exists(file_path):
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="application/vnd.ms-excel")
            response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
            return response
    raise Http404

def test_500_error(request):
    # Return an "Internal Server Error" 500 response code.
    return HttpResponse(status=500)

def test_404_error(request):
    # Return an "Internal Server Error" 404 response code.
    return HttpResponse(status=404)

def test_407_error(request):
    # Return an "Internal Server Error" 407 response code.
    return HttpResponse(status=407)

MyWiki/wiki/templates/wiki/base.html
{% load static %}
<!DOCTYPE html>
<html>
{# Applies the head to the pages base #}
{% include "wiki/head.html" %}

<body>
    {# Applies the header to the pages base #}
    {% include 'wiki/header.html' %}

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
    </ul>
    {% endif %}

{% block content %}
    NO CONTENT PROVIDED
    {% block contentTitle %}
    {% endblock %}
{% endblock content %}

{# Applies the footer to the pages base #}
    {% include 'wiki/footer.html' %}
{# Applies the scripts to the pages base #}
    {% include 'wiki/scripts.html' %}

</body>

</html>

MyWiki/wiki/templates/wiki/create_page.html
{% extends "wiki/base.html" %}

{% block content %}
    {# Displays the pages title #}
    <h1 class="text-center">{{page_name}}</h1>
    {# Provides some descriptive text. #}
    <p class="text-center">This page does not exist.</p>
    {# Creates the page then pressed. #}
    <a  class="btn btn-primary"
        href="{% url 'wiki:edit_page' page_name %}"
        style="margin-left:10%;">
    Create?
    </a>
{% endblock %}

MyWiki/wiki/templates/wiki/delete_page.html
{% extends "wiki/base.html" %}

{% block content %}
{# Displays a heading for the page #}
<h1 class="text-center" style="margin: 0 20% 0 20%;">Are you sure you want to delete the following page:</h1>
<br>
{# Displays the pages title #}
<h2 class="text-center"><strong>{{ page_name }}</strong></h2>

{# Uses a model form to redirect the user when the button is pressed to confirm page deletion #}
<form method='POST' class="text-center" action="{% url 'wiki:delete_confirm' page_name %}">
    {% csrf_token %}
    <br>
    <button class='btn btn-danger' name="Delete" type="submit" value="Delete" style="width:20%;">Yes, delete</button>
</form>
{% endblock %}

MyWiki/wiki/templates/wiki/detail.html
{% extends "wiki/base.html" %}
{% load static %}

{% block content %}
{% load wiki_tags %}
{# Displays the pages title #}
<h2 class="text-primary text-center">{{ page.title }}</h2>

<div style="margin: 30px 10%;">
        {# Button to allow them to edit the current page #}
    <a class="btn btn-primary" href="{% url 'wiki:edit_page' page.title %}">Edit</a>
    {# Returns the user to the index page. #}
    <a class="btn btn-primary" href="{% url 'wiki:index' %}" style="position: absolute; right: 0; margin-right:10%;">Go
        Back</a>
</div>
<div class="card" style="margin: 10px 5%; padding: 10px;">
    {# Displays a filtered version of the content to allow markup and remove html tags provided by the input #}
    {{page.content | titleValidator | markup | safe}}
</div>
<div style="margin: 30px 10%;">
    {# Button to allow them to edit the current page #}
    <a class="btn btn-primary" href="{% url 'wiki:edit_page' page.title %}">Edit</a>
    {# Returns the user to the index page. #}
    <a class="btn btn-primary" href="{% url 'wiki:index' %}" style="position: absolute; right: 0; margin-right:10%;">Go
        Back</a>
</div>
{# Displays a counter to show how many times the page has been visited. This is required by the brief. #}
<div class="text-center">This Page has been visited {{page.counter}} times.</div>
{% endblock %}

MyWiki/wiki/templates/wiki/edit_page.html
{% extends "wiki/base.html" %} 
{% load staticfiles %} 

{% block content %}
<header>
    {# Displays the pages title #}
    <h3 class="text-center">Editing: {{ page_name }}</h3>
</header>
{# Form for the user to modify the pages content #}
<form method="post" action="{% url 'wiki:save_page' page_name %}">
    {% csrf_token %}
    <div class="text-center">
        <input class="btn btn-primary" name="Save" type="submit" value="Save" style="margin-right:15%; display: inline-block; min-width: 150px;">
        <button class="btn btn-primary" name="Cancel" style="right: 0; margin-left:15%; display: inline-block;  min-width: 150px; color: white;">Cancel</button>
    </div>
    <div style="margin: 20px 15% 10px 15%;">
        <textarea id="id_content" name="content" rows="10" style=" width: 100%; height: auto;">
{{content}}
        </textarea>
    </div>
    <br>

    <div class="text-center">
        <input class="btn btn-primary" name="Save" type="submit" value="Save" style="margin-right:5%; display: inline-block; min-width: 150px;">
        <button class="btn btn-primary" name="Cancel" style="right: 0; margin-left:5%; display: inline-block;  min-width: 150px; color: white;">Cancel</button>
    </div>
</form>
<hr>
{# Form for the user to delete the page #}
<form method="post" action="{% url 'wiki:delete_page' page_name %}" class="text-center" style="background-color: beige; border-radius: 10px; border: 2px solid black; padding-bottom: 20px; margin: 0 25% 0 25%;">
    {% csrf_token %}
    <br>
    <h5>Want to delete this post?</h5>
    <input class="btn btn-danger" name="Delete" type="submit" value="Delete" style="width:250px;">
</form>
{% endblock %}

MyWiki/wiki/templates/wiki/footer.html
{% load static %}
{# Displays the pages footer #}
<!-- Footer -->
<footer class="page-footer font-small pt-1 text-white" style="background-color: #263238!important;">
  <!-- Footer Links -->
  <div class="container text-center text-md-left">
      <!-- Grid column -->
      <div class="col-md-12 mx-auto">
        <!-- Content -->
        <h5 class="font-weight-bold text-uppercase mt-2 mb-2 text-center" style="font-size:16px;">Footer Content</h5>
        <p style="font-size:14px; text-align: center;">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit,
            sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit.
          </p>
      </div>
  </div>
  {% if not request.user.is_authenticated %}
  <hr>
  <ul class="list-unstyled list-inline text-center py-1">
    <li class="list-inline-item">
      <h5 class="mb-1" style="font-size:18px;">Register for free</h5>
    </li>
    <li class="list-inline-item">
      <a href="{% url 'wiki:signup_page' %}" class="btn btn-danger btn-rounded">Sign up!</a>
    </li>
  </ul>
  {% endif %}
  <!-- Copyright -->
  <div class="footer-copyright text-center py-9" style="background-color: rgba(0,0,0,.2);;">
    <p style="padding: 15px 0 15px 0; margin-bottom:0px;">
      &copy; 2019. All rights reserved. MyWiki created by Andrew Tibbles.
    </p>
  </div>
  <!-- Copyright -->
</footer>

MyWiki/wiki/templates/wiki/head.html
{% load static %}
{# Sets the pages title and styles #}
  <head>
    <meta charset="utf-8">
    <title> MyWiki</title>
    <meta name="description" wiki="">
    <meta name="viewport" wiki="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'wiki/style.css' %}">

    <link rel="shortcut icon" href="{% static 'images/icon.png' %}">
  </head>

MyWiki/wiki/templates/wiki/header.html
<header class="header">
  {# Creates a navigation view with the use of bootstrap #}
  <!-- Main Navbar-->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'wiki:index' %}">MyWiki</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav text-center">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'wiki:index' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'wiki:upload_page' %}">upload</a>
        </li>
      </ul>
    </div>
  </nav>
</header>
<br />

MyWiki/wiki/templates/wiki/index.html
{% extends 'wiki/base.html' %}
{% load static %}

{% block content %}

{% if request.user.is_authenticated %}
<a href="{% url 'wiki:logout' %}" class="btn btn-primary float-right mr-5">logout</a>
<br>
<p class="text-center col-sm-2 float-right mr-5" style="padding:5px; background:#e9ecef; border:1px solid black; border-radius: 10px;">Welcome <span style="font-weight:bold;">{{ request.user.username|upper }}</span></p>
{% else %}
<a href="{% url 'wiki:login' %}" class="btn btn-primary float-right mr-5">login</a>
{% endif %}
<section style="margin-top:75px;">
    <div class="container jumbotron text-center">
        <div class="row">
            <div class="col-lg-12">
                <h1>MyWiki</h1>
            </div>
        </div>
    </div>
</section>
<!-- Intro Section-->
<section class="intro">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2 class="h3 text-center">Introduction</h2>
                <p class="text-big">
                    An <strong>introduction</strong> here <strong>to catch reader's
                    attention</strong>. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud nisi ut
                    aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderi.
                </p>
            </div>
        </div>
    </div>
</section>

<!-- Index Section-->
<section class="wiki">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2 class="h3 text-center">Index</h2>
                {# Checks for any pages #}
                {% if pages %}
                <div class="card text-center">
                    <ul class="list-group list-group-flush">
                        {# Loops for each page to create a list of pages in the wiki #}
                        {% for page in pages %}
                        <li class="list-group-item">
                            {# Display a link with each pages title. #}
                            <a href="{% url 'wiki:detail' page.title %}">
                                {{ page.title }}
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                {# In the case that there are no pages present on the database display the following text #}
                {% else %}
                <p>There are currently no wiki's available.</p>
                {% endif %}
            </div>
            <p style="margin-top:20px;"> The create page button is not implemeted yet use the url /&lt;your-page&gt;/</p>
            <a class="btn btn-primary" href="#" style="margin:15px 10% 10px auto;">
                Create Page
            </a>
        </div>
    </div>
    <br>
    {# Displays the browser used to render the page. This is part required by the brief. #}
    <p class="text-center">The browser used to load this page is {{ request.META.HTTP_USER_AGENT }}</p>
    <!--<img src="{% static 'wiki/image/yellowbubble.png' %}" style="margin: 10px 30% 10px 30%;" />-->
    <button style="margin-left:40%;" onclick="myFunction()">Get Screen Resolution</button>
    <p id="demo" class="text-center"></p>
</section>
<script>
        function myFunction() {
          var x = "Screen Resolution:\n" + "Total Width: " + screen.width + "px, " + "Total Height: " + screen.height + "px ";
          document.getElementById("demo").innerHTML = x;
        }
        </script>
{% endblock %}

MyWiki/wiki/templates/wiki/results.html
<h1>{{ page.title }}</h1>

<ul>
{% for choice in page.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'wiki:detail' page.id %}">Vote again?</a>

MyWiki/wiki/templates/wiki/scripts.html
{% load static %}
{# Used to define and configure scripts. This is defined at the bottom of the bases html page. #}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

<script src="{% static 'wiki/scripts/tinymce.min.js' %}"></script>
<script>tinymce.init({
        selector: '#id_content',
        plugins: [
            'advlist autolink lists link image charmap preview hr anchor pagebreak',
            'searchreplace wordcount visualblocks visualchars code',
            'insertdatetime media nonbreaking table contextmenu directionality autoresize',
            'emoticons template paste textcolor colorpicker  imagetools codesample'
        ],
       
        toolbar: 'codesample | bold italic sizeselect fontselect fontsizeselect | hr alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | insertfile undo redo | forecolor backcolor emoticons | code',
        fontsize_formats: "8pt 10pt 12pt 14pt 18pt 24pt 36pt",
        menubar: false
    });
</script>

MyWiki/wiki/templates/wiki/updatepage.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

MyWiki/wiki/templates/wiki/upload.html
{% extends 'wiki/base.html' %}
{% load static %}

{% block content %}
{% block contentTitle %}<h2 class="text-center" style="font-weight: bold;">File Upload</h2>{% endblock %}
<section>
    <h5 style="margin-left:15%;">Uploaded Files:</h5>
    <div class="d-flex justify-content-center uploaded">
        {# Print a list of all found files #}
        {% if files %}
        <table colspan="2" width="90%" class="border">
                <tr class="border" >
                  <th width="60%" class="text-center border">File</td>
                  <th width="40%" class="text-center border" >Download</td> 
                </tr>
              {% for file in files %}
                <tr class="border">
                  <td width="60%" lass="border"><a href="{{file.upload.url}}">{{file.upload.name}}</a></td>
                  <td width="40%"class="text-center border" ><a href="/download/{{file}}" style="text-decoration:None">Download here</a></td>
                </tr>
              {% endfor %}  
              {# If no files found print text #}
              {% else %}
              <p>No uploaded files</p>
              {% endif %}
             </table>    
    </div>
    <br>
    <section>
        <h5 style="margin-left:15%;">Upload Files:</h5>

        <form class="text-center" method='POST' enctype='multipart/form-data' action="{% url 'wiki:upload_page' %}">
            {% csrf_token %}
            <div class="custom-file mb-3" style="margin: 10px 25% 10px 25%;">
                <div class="w-50 file-input custom-file-label">
                    {{form.upload}}
                </div>
            </div>
            <input type='submit' value="Upload">
        </form>
    </section>
    <style>
        .file-input>input[type="file"] {
            pointer-events: all;
            cursor: pointer;
        }

        .file-input>input::-webkit-file-upload-button {
            visibility: hidden;
        }
        .uploaded ul{ list-style-type: none; }
        .uploaded li{
            border: lightslategray 1px solid;
            border-radius: 10px;
            padding-right:150px;
            padding-left:150px;
            padding-top:5px;
            padding-bottom:5px;
            margin-top:10px;
            text-align: center;
        }

        .border {
            border:black 1px solid;
            border-radius: 10px;
        }
    </style>
    {% endblock %}